version: 1.0.{build}

before_build:

- cmd: >-
   curl -fsSL -o "LLVM-12.0.1-win64.exe" "https://github.com/llvm/llvm-project/releases/download/llvmorg-12.0.1/LLVM-12.0.1-win64.exe"
   
   LLVM-12.0.1-win64.exe /S
    
    clang-cl -v
  
    
    mkdir build



    cd build



    cmake ..  -T "llvm"
build:
  verbosity: minimal
