environment:
  matrix:
    ###########################################################################
    # Build 64 bit version using clang-cl backed by MSVC 2017
    # -------------------------------------------------------------------------
    # Note that building against MSVC 2017 is only supported with a newer clang
    ###########################################################################
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      MSVC_SETUP_PATH: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat
      MSVC_SETUP_ARG: x64
      USE_CLANG: ON
version: 1.0.{build}
before_build:
- cmd: >-
    clang --version

    mkdir build

    cd build

    cmake .. -A x64
build:
  verbosity: minimal
