environment:
  matrix:
    ###########################################################################
    # Build x86 version using MSVC 2017
    ###########################################################################
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      MSVC_SETUP_PATH: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat
      MSVC_SETUP_ARG: x86
    ###########################################################################
    # Build x64 version using MSVC 2017
    ###########################################################################
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      MSVC_SETUP_PATH: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat
      MSVC_SETUP_ARG: x64
    ###########################################################################
    # Build 64 bit version using clang-cl backed by MSVC 2017
    # -------------------------------------------------------------------------
    # Note that building against MSVC 2017 is only supported with a newer clang
    ###########################################################################
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      MSVC_SETUP_PATH: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat
      MSVC_SETUP_ARG: x64
      USE_CLANG: ON
      INSTALL_NEW_CLANG: ON
      CLANG_URL: http://llvm.org/pre-releases/win-snapshots/LLVM-5.0.0-r301646-win64.exe
    ###########################################################################
    # Build 32 bit version using clang-cl backed by MSVC 2017
    ###########################################################################
    # FIXME: This is currently broken with CMake and Ninja. Likely a CMake bug
    # - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    #  MSVC_SETUP_PATH: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat
    #  MSVC_SETUP_ARG: x86
    #  USE_CLANG: ON
    #  INSTALL_NEW_CLANG: ON
    #  CLANG_URL: http://llvm.org/pre-releases/win-snapshots/LLVM-5.0.0-r301646-win64.exe
    ###########################################################################
    # Build 64 bit version using clang-cl backed by MSVC 2015
    ###########################################################################
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      MSVC_SETUP_PATH: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat
      MSVC_SETUP_ARG: x86_amd64
      USE_CLANG: ON
    ###########################################################################
    # Build using MSVC 2015
    ###########################################################################
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      MSVC_SETUP_PATH: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat
      MSVC_SETUP_ARG: x86_amd64
version: 1.0.{build}
before_build:
- cmd: >-
    clang --version

    mkdir build

    cd build

    cmake .. -A x64
build:
  verbosity: minimal
